### ISSUE TITLE
Unable to export graph as ensemble when using multi-hot categorical column

### ISSUE THREAD

**Issue by mkumari-ed** [NVIDIA-Merlin/Merlin#361] opened 2022-06-02 16:13 UTC
I am using inference container 22.05. When materializing feast in cell 6 [deploying multi-stage recsys notebook](https://github.com/NVIDIA-Merlin/Merlin/blob/main/examples/Building-and-deploying-multi-stage-RecSys/02-Deploying-multi-stage-RecSys-with-Merlin-Systems.ipynb), I am getting exception while materializing user_features. Item features worked just fine. Please download the sample data and notebooks used for this [from the link here](https://drive.google.com/drive/u/1/folders/1IK-2P6SqkdT-sxDUn0PRmprih2xNQXOa)

Using tensorflow-inference 22.05 container. Attaching the error here
![Screen Shot 2022-06-02 at 6 47 45 AM](https://user-images.githubusercontent.com/28987826/171676161-e01feef0-47d1-48b1-8932-faaacc10c881.png)

**Comment by rnyak** [comment] 2022-06-15 14:18
Closing this since materialization issue was solved. And another bug was reported here  https://github.com/NVIDIA-Merlin/systems/issues/115

**Comment by mkumari-ed** [comment] 2022-07-21 16:34
@karlhigley and @rnyak
I tested it out with my correct data today. I am attaching all screenshots for visibility. With the list of strings feature(for ex. ['sipl_camera', 'build qnx', 'yuv', 'dl g']), I am unable to materialize the user features using feast. The error that I get is ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all(). Also, attaching the user features sample and output of train_tt.to_ddf().compute() here along with the snapshot of how the raw data looks like
![materialize user features error](https://user-images.githubusercontent.com/28987826/180266815-e5c69848-3200-41eb-8dde-5d1c30d07036.png)
![raw data sample](https://user-images.githubusercontent.com/28987826/180266847-3b25f999-056e-40d0-b86d-1f3807fef1e6.png)
![train tt sample](https://user-images.githubusercontent.com/28987826/180266848-8d905308-d7c6-417f-814d-06d45536505b.png)
![user features sample](https://user-images.githubusercontent.com/28987826/180266851-6d4ddbf5-1ec5-4dbc-805e-c2b87f3c0fed.png)

**Comment by mkumari-ed** [comment] 2022-07-21 20:12
So going back to our conversation in the past, I used `INT32_LIST` dtype for this list type column instead of `INT32` and I was able to materialize as well as use queryfeast operator in the successive steps. However it leads to another error now on the step where we create retrieval object using PredictTensorflow object.
![Screen Shot 2022-07-21 at 1 08 36 PM](https://user-images.githubusercontent.com/28987826/180306652-e90c9887-5680-40e9-8a16-fd8f3f4a139f.png)
![Screen Shot 2022-07-21 at 1 08 55 PM](https://user-images.githubusercontent.com/28987826/180306666-628af9c4-2306-44c0-9095-bbf2a33b7e8e.png)

**Comment by karlhigley** [comment] 2022-07-27 15:42
What does `model._saved_model_inputs_spec` look like for your retrieval model?

**Comment by mkumari-ed** [comment] 2022-07-28 19:21
@karlhigley  In order to get the output of the above, I went and ran the pipeline again. But now, I am getting a different error at the step where I am fitting the model. Attaching the screenshots here.  I do get this error with and without including the list of strings feature column now. So I couldn't get to a point where I got the output of `model._saved_model_inputs_spec` to share it with you.
![Screen Shot 2022-07-28 at 12 19 31 PM](https://user-images.githubusercontent.com/28987826/181620022-86d70d22-55cd-420b-86d1-90afc61421c3.png)
![Screen Shot 2022-07-28 at 12 19 10 PM](https://user-images.githubusercontent.com/28987826/181620013-a5c5899e-2720-4c92-a54b-208b010f3c9e.png)

**Comment by mkumari-ed** [comment] 2022-07-28 19:27
I have filed a new bug for the same: https://github.com/NVIDIA-Merlin/Merlin/issues/488

**Comment by mkumari-ed** [comment] 2022-07-28 20:27
@karlhigley  here is the output for the retrieval model
`{'search': (TensorSpec(shape=(727237, 1), dtype=tf.int32, name='search_1'), TensorSpec(shape=(16384, 1), dtype=tf.int32, name='search_2')), 'userid': TensorSpec(shape=(16384, 1), dtype=tf.int32, name='userid'), 'contentid': TensorSpec(shape=(16384, 1), dtype=tf.int32, name='contentid'), 'eventtype': TensorSpec(shape=(16384, 1), dtype=tf.int32, name='eventtype'), 'eventStrength': TensorSpec(shape=(16384, 1), dtype=tf.int32, name='eventStrength'), 'ts': TensorSpec(shape=(16384, 1), dtype=tf.int32, name='ts'), 'spaceid': TensorSpec(shape=(16384, 1), dtype=tf.int32, name='spaceid'), 'spacekey': TensorSpec(shape=(16384, 1), dtype=tf.int32, name='spacekey'), 'spacename': TensorSpec(shape=(16384, 1), dtype=tf.int32, name='spacename'), 'parenttitle': TensorSpec(shape=(16384, 1), dtype=tf.int32, name='parenttitle'), 'parentid': TensorSpec(shape=(16384, 1), dtype=tf.int32, name='parentid'), 'mgrntaccount': TensorSpec(shape=(16384, 1), dtype=tf.int32, name='mgrntaccount'), 'businessarea': TensorSpec(shape=(16384, 1), dtype=tf.int32, name='businessarea'), 'jobposition': TensorSpec(shape=(16384, 1), dtype=tf.int32, name='jobposition'), 'hrrolename': TensorSpec(shape=(16384, 1), dtype=tf.int32, name='hrrolename'), 'location': TensorSpec(shape=(16384, 1), dtype=tf.int32, name='location')}`

**Comment by karlhigley** [comment] 2022-07-29 13:43
I think the issue is happening while trying to get the `shape` of the `search` field, which looks like it might be in `values`/`offsets` format to handle variable length lists per example in the batch?

**Comment by karlhigley** [comment] 2022-07-29 14:41
@mkumari-ed Any chance you could share the model definition code and/or TF saved model file you're using to help me replicate the issue? (Slack would be fine if that works better.)

**Comment by mkumari-ed** [comment] 2022-07-29 16:23
@karlhigley  Hi Karl, I just reached out to you on slack with file links and follow up questions. Please let me know.

**Comment by mkumari-ed** [comment] 2022-08-02 20:25
Currently getting error at the step where we export graph as ensemble on search column.
![Screen Shot 2022-08-01 at 3 38 48 PM](https://user-images.githubusercontent.com/28987826/182466775-232cf3d0-1012-4830-bb1e-51ec6aac1b56.png)
![Screen Shot 2022-08-01 at 3 39 11 PM](https://user-images.githubusercontent.com/28987826/182466779-5ee753a5-86d9-4381-92ba-88efc19745f2.png)

**Comment by mkumari-ed** [comment] 2022-08-03 16:21
@karlhigley  Hi Karl, renaming the column from `search` to `search_1` didn't help in resolving the error that I get currently while exporting the graph as ensemble. It now complains of the missing `search_1` column in operatorSubsetColumns. 
![Screen Shot 2022-08-01 at 3 39 11 PM](https://user-images.githubusercontent.com/28987826/182659356-c27ebea9-e7e7-48e5-941d-070a16a8fa15.png)
Here is the screenshot

**Comment by viswa-nvidia** [comment] 2022-08-04 18:16
@karlhigley , the last comment shows that the issue is not resolved. But status is done. I have moved it to WIP. Please review

**Comment by karlhigley** [comment] 2022-08-04 22:33
This is no longer the same (original) issue, which is why it was marked as done.

**Comment by viswa-nvidia** [comment] 2022-08-15 16:58
@mkumari-ed , the original issue is done. But we cannot close this because other issues have been added to the thread. Please create separate tickets and let us know and we. will close this ticket. Thank you.

**Comment by EvenOldridge** [comment] 2022-10-17 23:50
Closing.  @mkumari-ed please create additional issues if you're still experiencing this.

**Closed by EvenOldridge** 2022-10-17 23:50 UTC
Labels: bug, P0
