### ISSUE TITLE
[RMP] RecSys Tutorial

### ISSUE THREAD

**Issue by karlhigley** [NVIDIA-Merlin/Merlin#270] opened 2022-05-04 15:20 UTC
- [ ] What's the scope of this tutorial?
- [ ] Will it include?
  - [ ] Retrieval/ranking models
  - [ ] Transformer models (in MM?)
  - [ ] XGBoost/FIL
  - [ ] Merlin Systems

**Comment by karlhigley** [comment] 2022-05-04 15:20
@bschifferer @rnyak Have we already submitted a proposal for this tutorial? If so, could we link to it from this issue?

**Comment by bschifferer** [comment] 2022-05-04 15:41
The proposal deadline is May 18th. We will work on it this and next week

**Comment by EvenOldridge** [comment] 2022-07-04 21:45
@bschifferer @rnyak Is this a duplicate of https://github.com/NVIDIA-Merlin/Merlin/issues/286

**Closed** 2022-07-15 19:37 UTC
