### ISSUE TITLE
[RMP] Merlin Models PyTorch API

### ISSUE THREAD

**Issue by viswa-nvidia** [NVIDIA-Merlin/Merlin#534] opened 2022-08-10 00:03 UTC
Note: This ticket needs to capture the models related work also. 

## Problem:
Adding PyT api to Merlin models

## Starting Point:
[[RMP] Provide serving support for PyTorch models](https://github.com/NVIDIA-Merlin/Merlin/issues/255)

- [ ] Enable Distributed Data Parallel training
  - [ ] Next item prediction
  - [ ] Binary classification

- [ ] Example of how to migrate between Transformers4Rec to Merlin Models

**Comment by viswa-nvidia** [comment] 2022-11-29 18:11
@marcromeyn please define the ticket

**Comment by EvenOldridge** [comment] 2023-04-27 17:44
Duplicate of #893

**Closed by EvenOldridge** 2023-04-27 17:44 UTC
Labels: roadmap
