### ISSUE TITLE
[ERMP] Make embedding layers more performant and scalable

### ISSUE THREAD

**Issue by viswa-nvidia** [NVIDIA-Merlin/Merlin#412] opened 2022-06-22 14:22 UTC
## Problem
Customers need to be able to train models that exceed the memory of a single GPU. Recommender Systems models can grow to over hundreds of millions of users and items , which isn’t feasible to store on a single GPU.

## Goal
- HugeCTR SOK  implementation in Models library
- Make embedding layers more performant - ( Based on JoC example - 40% more efficient )
- 

##Stories
- [ ] https://github.com/NVIDIA-Merlin/Merlin/issues/404
- [ ] https://github.com/NVIDIA-Merlin/models/issues/451
- [ ] Performance improvement of the embedding tables

**Comment by EvenOldridge** [comment] 2022-07-04 22:23
Closing as a duplicate of https://github.com/NVIDIA-Merlin/models/issues/415

**Closed by EvenOldridge** 2022-07-04 22:23 UTC
