### ISSUE TITLE
[BUG] hugectr not available in merlin-inference and merlin-tensorflow-training

### ISSUE THREAD

**Issue by mattf** [NVIDIA-Merlin/Merlin#161] opened 2022-03-25 21:16 UTC
merlin-inference -

```bash
$ docker run --rm -it nvcr.io/nvidia/merlin/merlin-inference:22.03 python -c 'import hugectr'

==========
== CUDA ==
==========

NVIDIA Release  (build )
CUDA Version 11.6.0.021

Container image Copyright (c) 2022, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use the NVIDIA Container Toolkit to start this container with GPU support; see
   https://docs.nvidia.com/datacenter/cloud-native/ .

NOTE: MOFED driver for multi-node communication was not detected.
      Multi-node communication performance may be reduced.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'hugectr'
```

merlin-tensorflow-training -

```bash
$ docker run --rm -it nvcr.io/nvidia/merlin/merlin-tensorflow-training:22.03 python -c 'import hugectr'

================
== TensorFlow ==
================

NVIDIA Release 22.02-tf2 (build 32333867)
TensorFlow Version 2.7.0

Container image Copyright (c) 2022, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
Copyright 2017-2022 The TensorFlow Authors.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use the NVIDIA Container Toolkit to start this container with GPU support; see
   https://docs.nvidia.com/datacenter/cloud-native/ .

NOTE: MOFED driver for multi-node communication was not detected.
      Multi-node communication performance may be reduced.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'hugectr'
```

**Comment by karlhigley** [comment] 2022-03-25 22:06
I think HugeCTR should be available in the `merlin-training` and `merlin-inference` containers, and should not be available in the `merlin-tensorflow-training` container. Is that right, @albert17?

**Comment by mattf** [comment] 2022-03-26 11:31
https://github.com/NVIDIA-Merlin/Merlin/blob/main/docker/README.md (as of https://github.com/NVIDIA-Merlin/Merlin/commit/fa1b8c4b84b00c78cc6b1a7dcd59a93694e5ecb0) says `-training`, `-tensorflow-training`, and `-inference`

![image](https://user-images.githubusercontent.com/112653/160237372-c93762de-7963-4f90-966d-6cfe790dd150.png)

i can only confirm it is in `-training`

**Comment by karlhigley** [comment] 2022-03-26 17:40
I think what that's trying to say is "HugeCTR Tensorflow Embedding plugin," which doesn't actually mean that HugeCTR itself is available there, if I understand correctly. Maybe we can clarify this though?

cc @mikemckiernan @albert17

**Comment by mattf** [comment] 2022-03-28 12:58
if that's the intention of the documentation, it should be clarified. the line break is unfortunate too.

this would leave the issue that HugeCTR is not available in there `-inference` container

**Comment by karlhigley** [comment] 2022-03-28 18:46
The second part is a duplicate of https://github.com/NVIDIA-Merlin/Merlin/issues/142, which has been addressed in the nightly images (see https://github.com/NVIDIA-Merlin/Merlin/pull/135.)

**Comment by mattf** [comment] 2022-03-28 19:04
```
$ docker run --rm -it nvcr.io/nvidia/merlin/merlin-inference:nightly python -c 'import hugectr' | tail -n3
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'hugectr'
```
is this an issue where "HugeCTR" in the `merlin-inference` container really means "HugeCTR Tensorflow Embedding plugin"

**Comment by karlhigley** [comment] 2022-03-28 20:10
I don't think that's expected to work on the inference container; what it has is the [Triton Inference Server HugeCTR Back-end](https://github.com/triton-inference-server/hugectr_backend) for serving. (Correct me if I'm wrong here, @albert17.)

**Comment by viswa-nvidia** [comment] 2022-08-11 00:53
@karlhigley , can we close this issue ? If not, please assign a priority

**Closed** 2022-08-11 01:06 UTC
Labels: documentation
