### ISSUE TITLE
[RMP] Filter out previously interacted items

### ISSUE THREAD

**Issue by viswa-nvidia** [NVIDIA-Merlin/Merlin#108] opened 2022-02-17 05:58 UTC
# Merlin-models(Data Scientist)
Integrated filtering?

# NVTabular(Data Scientist)

# Merlin-systems(Product Engineer)
Operators for applying filters during serving/batch

# Merlin-orchestration(Infra Engineer)
Build Bloom filters

# Examples and Docs(Everyone)

Aha! Link: https://nvaiinfa.aha.io/features/MERLIN-825

**Comment by karlhigley** [comment] 2022-02-17 21:02
We should probably consider this part of #102, since it doesn't matter if we have an ensemble API if we don't also have the essential building blocks to put in an ensemble

**Comment by EvenOldridge** [comment] 2022-12-14 18:32
Duplicate of #703

**Closed by EvenOldridge** 2022-12-14 18:32 UTC
Labels: roadmap, epic
