### ISSUE TITLE
[RMP] Larger than GPU memory embedding tables

### ISSUE THREAD

**Issue by viswa-nvidia** [NVIDIA-Merlin/Merlin#107] opened 2022-02-17 05:56 UTC
# Merlin-models(Data Scientist)
GPU Embedding cache and parameter server integration

# NVTabular(Data Scientist)

# Merlin-systems(Product Engineer)
GPU Embedding cache and parameter server integration

# Merlin-orchestration(Infra Engineer)

# Examples and Docs(Everyone)

Aha! Link: https://nvaiinfa.aha.io/features/MERLIN-826

**Comment by EvenOldridge** [comment] 2022-08-17 22:57
Duplicate of https://github.com/NVIDIA-Merlin/models/issues/415

**Closed by EvenOldridge** 2022-08-17 22:57 UTC
Labels: roadmap, epic

**Comment by karlhigley** [comment] 2022-08-18 13:55
Am I wrong in thinking we want all the RMP issues on the Merlin repo?
